name: Lint
on: push
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Flake8
        run: pip install flake8==3.7.7
      - name: Run Flake8
        run: flake8 . --show-source --statistics
